[build]
  publish = "public"
  command = "hugo --themesDir themes"

[build.environment]
  HUGO_VERSION = "0.83.1"
  HUGO_THEME = "repo"
  HUGO_BASEURL = "https://papercss-hugo-theme.netlify.app"

[[headers]]
  for = "/*"
    [headers.values]
      Access-Control-Allow-Origin = "*"
